// console.log("Its index.js, entry level file.");

console.log("################################# Node JS ###############################");
    console.log("1) basicConcept.js");
    console.log("2) coreModule.js");
    console.log("3) thirdPartyPackage.js");
    console.log("4) myServer.js");
    console.log("5) data.js");
    console.log("6) simpleApi.js");
    console.log("7) inputFromConsole.js");
    console.log("8) readDirFilenames.js");
    console.log("9) fileOperations.js");
    console.log("10) asyncBasics.js");
    console.log("11) myPromiseThen.js");
console.log("################################# Node JS ###############################");

console.log("################################# Express Js ###############################");
    console.log("12) myExpressPackage.js");
    console.log("13) routeParams.js");
    console.log("14) renderHtmlnJson.js");
    console.log("15) renderHtmlPage.js");
    console.log("16) removeExtension.js");
    console.log("17) handle404Page.js");
    console.log("18) expressMiddleware.js");
    console.log("19) middleware.js");
    console.log("20) routeLevelMiddleware.js");
console.log("################################# Express Js ###############################");

console.log("################################# MongoDB (Mongoose) ###############################");
    console.log("21) myMongoose.js");
    console.log("22) mongooseSchemaModel.js");
    console.log("23) insertDocument.js");
    console.log("24) multipleInsertDocument.js");
    console.log("25) getDocument.js");
    console.log("26) comparisonOperators.js");
    console.log("27) logicalOperators.js");
    console.log("28) sortCountMethods.js");
    console.log("29) updateDocument.js");
    console.log("30) deleteDocument.js");
    console.log("31) mongooseBuildInValidation.js");
    console.log("31) mongooseCustomValidation.js");
    console.log("31) myValidatorPackage.js");
console.log("################################# MongoDB (Mongoose) ###############################");